version: '3'

services:
  web:
    image: wordpress:php7.2
    depends_on:
      - db
    ports:
    - 80:80
    restart: always
    volumes:
      - ./wordpress:/var/www/html/wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: newpassword
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: wordpress
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
      MYSQL_DATABASE: wordpress
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  db_data:
  wordpress:
